export interface vtorApp {
    id: string,
    bannerColor: string,
    appHeading: string,
    appNote: string,
    appDemoImage: string,
    appDescription_Title1: string,
    appDescription_1: string,
    appDescription_Title2: string,
    appDescription_2: string,
    appWorkingImage: string,
    appWorkingDescription: string,
    appPlusPoint_1: string,
    appPlusPoint_2: string,
    appPlusPoint_3: string,
    appPlusPoint_4: string,
    appImage_1: string,
    appImage_2: string,
    appImage_3: string,
    appImage_4: string,
    appName: string,
    appShortDesc: string,
}